# Generated by Django 3.2 on 2023-05-12 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20230510_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category'),
        ),
    ]
