# Generated by Django 3.2 on 2023-05-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_new_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='category',
        ),
        migrations.AddField(
            model_name='new',
            name='category',
            field=models.ManyToManyField(null=True, to='news.Category'),
        ),
    ]
